### ISSUE TITLE
Create a variety of projectiles/bullets

### ISSUE THREAD

**Issue by NJHewadewa** [NJHewadewa/DebtRunners#6]
Advice would be to extend the bullet class to bullets of different attributes.
I'm still looking into modelling/structuring all of our objects in a better way so chances are I will play around with this.

**Comment by NJHewadewa** [comment]
Homing bullets

**Comment by rubbertoe98** [comment]
boss battle - big ball bullet slowing moving (homing) and can be shot and de_stroyed
